### ISSUE TITLE
Change Tower colors

### ISSUE THREAD

**Issue by matthewcheung8** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#44] opened 2016-03-10 23:57 UTC
Change the color of the Tower that you clicked so it shows which tower you are on.
100 points

**Comment by ashedden** [comment] 2016-03-11 22:08
W16 ok!

**Comment by jalexanderqed** [comment] 2016-09-29 16:04
F16 CLOSED: Duplicate of #32

**Closed by jalexanderqed** 2016-09-29 16:04 UTC
